name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    outputs:
      should_run: ${{ steps.filter.outputs.workflows == 'true' || steps.filter.outputs.aqua == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Check for relevant changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
            aqua:
              - '.aqua/**'

  check:
    name: Check
    needs: changes
    if: needs.changes.outputs.should_run == 'true'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install aqua
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        env:
          AQUA_CONFIG: ".aqua/aqua.yaml"
        with:
          aqua_version: "v2.55.2"
      - name: Run pinact
        run: pinact run --check
      - name: Run actionlint
        run: actionlint
