name: Renovate Validate

on:
  push:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/validate-renovate.yml"
  pull_request:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/validate-renovate.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-renovate-config:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0

      - name: Validate Renovate config
        run: npx --package renovate -- renovate-config-validator --strict renovate.json5
